
/* jobs list */
export const FETCH_JOBS_STARTED = 'FETCH_JOBS_STARTED';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const DELETE_JOB_STARTED = 'DELETE_JOB_STARTED';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const ADD_JOB_STARTED = 'ADD_JOB_STARTED';
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS';

/* environment step */
export const FETCH_ENVIRONMENT_DATA_STARTED = 'FETCH_ENVIRONMENT_DATA_STARTED';
export const FETCH_ENVIRONMENT_DATA_SUCCESS = 'FETCH_ENVIRONMENT_DATA_SUCCESS';
export const SET_ENVIRONMENT_STEP_DATA = 'SET_ENVIRONMENT_STEP_DATA';
export const SET_ISVALID_ENVIRONMENT_DATA = 'SET_ISVALID_ENVIRONMENT_DATA';
export const SOURCENVIRONMENT_VALIDATION_START = 'SOURCENVIRONMENT_VALIDATION_START';
export const SOURCENVIRONMENT_VALIDATION_SUCCESS = 'SOURCENVIRONMENT_VALIDATION_SUCCESS';
export const TARGETENVIRONMENT_VALIDATION_START = 'SOURCENVIRONMENT_TARGETENVIRONMENT_START';
export const TARGETENVIRONMENT_VALIDATION_SUCCESS = 'TARGETENVIRONMENT_VALIDATION_SUCCESS';

/* environment step */
export const SET_ENVRIONMENT_STEP_VALIDITY = 'SET_ENVRIONMENT_STEP_VALIDITY';

/* sourceenvironment step */
export const FETCH_SOURCEENVIRONMENT_DATA_STARTED = 'FETCH_SOURCEENVRIONMENT_DATA_STARTED'
export const FETCH_SOURCEENVIRONMENT_DATA_SUCCESS = 'FETCH_SOURCEENVIRONMENT_DATA_SUCCESS'
export const SET_SOURCEENVIRONMENT_DATA = 'SET_SOURCEENVIRONMENT_DATA'

/* targetenvironment step */
export const FETCH_TARGETENVIRONMENT_DATA_STARTED = 'FETCH_TARGETENVIRONMENT_DATA_STARTED'
export const FETCH_TARGETENVIRONMENT_DATA_SUCCESS = 'FETCH_TARGETENVIRONMEN_DATA_SUCCESS'
export const SET_TARGETENVIRONMENT_DATA = 'SET_TARGETENVIRONMENT_DATA'

export const SET_VALIDATION_STATUS = 'SET_VALIDATION_STATUS';

/* entities step */
export const FETCH_ENTITIES_DATA_STARTED = 'FETCH_ENTITIES_DATA_STARTED';
export const FETCH_ENTITIES_DATA_SUCCESS = 'FETCH_ENTITIES_DATA_SUCCESS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ORDER = 'SET_ORDER';
export const SET_ORDER_BY = 'SET_ORDER_BY';
export const SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS';
export const SET_REPORTS = 'SET_REPORTS';

/* map users step */
export const SET_MAP_STEP_DATA = 'SET_MAP_STEP_DATA';
export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const SET_TARGET_USER = 'SET_TARGET_USER';
export const REMOVE_TARGET_FROM_SOURCE = 'REMOVE_TARGET_FROM_SOURCE';
export const USE_AUTOMAP = 'USE_AUTOMAP';
export const SET_TO_TARGET = 'SET_TO_TARGET';

/* map business units step */
export const FETCH_BUSINESS_UNITS_STARTED = 'FETCH_BUSINESS_UNITS_STARTED';
export const FETCH_BUSSINESS_UNITS_SUCCESS = 'FETCH_BUSSINESS_UNITS_SUCCESS';
export const SET_TARGET_BUSINESS_UNITS = 'SET_TARGET_BUSINESS_UNITS';
export const REMOVE_BUSINESS_TARGET_FROM_SOURCE = 'REMOVE_BUSINESS_TARGET_FROM_SOURCE';
export const SET_TO_BUSINESS_TARGET = 'SET_TO_BUSINESS_TARGET';
export const USE_BUSINESS_AUTOMAP = 'USE_BUSINESS_AUTOMAP';

/* map teams step */
export const FETCH_TEAMS_STARTED = 'FETCH_TEAMS_STARTED';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const SET_TARGET_TEAMS = 'SET_TARGET_TEAMS';
export const REMOVE_TEAMS_TARGET_FROM_SOURCE = 'REMOVE_TEAMS_TARGET_FROM_SOURCE';
export const SET_TO_TEAMS_TARGET = 'SET_TO_TEAMS_TARGET';
export const USE_TEAMS_AUTOMAP = 'USE_TEAMS_AUTOMAP';

/* summary step */
export const SET_SUMMARY_STEP_DATA = 'SET_SUMMARY_STEP_DATA';

/* steps */
export const SET_STEP_VALIDITY = 'SET_STEP_VALIDITY';
export const SET_ENVIRONMENT_DATA = 'SET_ENVIRONMENT_DATA';

/* validation */
export const SET_VALIDATION_INIT = 'SET_VALIDATION_INIT';
export const SET_VALIDATION_START = 'SET_VALIDATION_START';
export const SET_VALIDATION_SUCCESS = 'SET_VALIDATION_SUCCESS';
export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';

/* other */
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SETTINGS_INIT_STARTED = 'SETTINGS_INIT_STARTED';
export const SETTINGS_INIT_SUCCESS = 'SETTINGS_INIT_SUCCESS';
export const SET_ISVALID_DATA = 'SET_ISVALID_DATA';
export const SET_JOB_STATUS = 'SET_JOB_STATUS';